# Generated by Django 4.2.2 on 2023-06-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0004_updated_createdAt_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notemodel',
            options={'ordering': ['-createdAt']},
        ),
    ]
